// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgtUXywh5_CSfx37dgmwYd8hSVjspk-rU',
    appId: '1:393199727845:web:233bc96d32017b9ec0d00c',
    messagingSenderId: '393199727845',
    projectId: 'task-management-5655b',
    authDomain: 'task-management-5655b.firebaseapp.com',
    databaseURL: 'https://task-management-5655b-default-rtdb.firebaseio.com/',
    storageBucket: 'task-management-5655b.firebasestorage.app',
    measurementId: 'G-F32ZY5Y83B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSMEGUsFCf_aq55YnhZMO8CQu6LAho80',
    appId: '1:393199727845:android:e851df53f45cdf72c0d00c',
    messagingSenderId: '393199727845',
    projectId: 'task-management-5655b',
    databaseURL: 'https://task-management-5655b-default-rtdb.firebaseio.com/',
    storageBucket: 'task-management-5655b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCAmqKOsY07_FaGP5rJHweOm4AVDZ13As',
    appId: '1:393199727845:ios:8277c1a856568189c0d00c',
    messagingSenderId: '393199727845',
    projectId: 'task-management-5655b',
    databaseURL: 'https://task-management-5655b-default-rtdb.firebaseio.com/',
    storageBucket: 'task-management-5655b.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCAmqKOsY07_FaGP5rJHweOm4AVDZ13As',
    appId: '1:393199727845:ios:8277c1a856568189c0d00c',
    messagingSenderId: '393199727845',
    projectId: 'task-management-5655b',
    storageBucket: 'task-management-5655b.firebasestorage.app',
    databaseURL: 'https://task-management-5655b-default-rtdb.firebaseio.com/',
    iosBundleId: 'com.example.taskmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgtUXywh5_CSfx37dgmwYd8hSVjspk-rU',
    appId: '1:393199727845:web:fba1c8966e29f662c0d00c',
    messagingSenderId: '393199727845',
    projectId: 'task-management-5655b',
    authDomain: 'task-management-5655b.firebaseapp.com',
    databaseURL: 'https://task-management-5655b-default-rtdb.firebaseio.com/',
    storageBucket: 'task-management-5655b.firebasestorage.app',
    measurementId: 'G-XB4XJ9QL3K',
  );
}
